# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Poole
tagline:          'The Jekylls Butler.'
description:      'A diligent and noble steward for building Jekyll sites.'
url:              http://roachhd.github.io/www

author:
  name:           'Katie Ball'
  url:            https://twitter.com/mektball

paginate:         5

# Custom vars
github:
  repo:           https://github.com/roachhd/www
